Script started on 2017年03月20日 (週一) 23時49分25秒
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab1 $[00m gpp[K[K++ -o labb.cpp [C[1@ [1@l[1@a[1@b[1@b[C[1@ [C[C[C[C[C[C[C[C[C[C
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab1 $[00m ./labb
22
22
11
34
17
52
26
13
40
20
10
5
16
8
4
2
1
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab1 $[00m exit

Script done on 2017年03月20日 (週一) 23時50分18秒
